

CREATE TABLE RequestMessage(
   ID INT PRIMARY KEY NOT NULL,
   IPADDRESS VARCHAR(255) NOT NULL,
   REQUESTNUMBER INT NOT NULL,
   DATEINSERTED date NOT NULL,
   TIME timestamp NOT NULL,
   MINIMUM int NOT NULL,
   LISTOFPARTICIPANTS VARCHAR(255) NOT NULL,
   TOPIC VARCHAR(255) NOT NULL
);

CREATE TABLE ResponseMessage(
   ID INT PRIMARY KEY NOT NULL,
   REQUESTNUMBER INT NOT NULL,
   IPADDRESS VARCHAR(255) NOT NULL
);

CREATE TABLE InviteMessage(
   ID INT PRIMARY KEY NOT NULL,
   IPADDRESS VARCHAR(255) NOT NULL,
   MEETINGNUMBER INT NOT NULL,
   DATEINSERTED date NOT NULL,
   TIME timestamp NOT NULL,
   TOPIC VARCHAR(255) NOT NULL,
   REQUESTER VARCHAR(255)  NOT NULL
);

CREATE TABLE AcceptMessage(
   ID INT PRIMARY KEY NOT NULL,
   MEETINGNUMBER INT NOT NULL,
   WHOACCEPTED VARCHAR(255) NOT NULL
);

CREATE TABLE RejectMessage(
   ID INT PRIMARY KEY NOT NULL,
   MEETINGNUMBER INT NOT NULL,
   WHOREJECTED VARCHAR(255) NOT NULL
);

CREATE TABLE ConfrimMessage(
   ID INT PRIMARY KEY NOT NULL,
   ROOMNUMBER VARCHAR(255) NOT NULL
);

CREATE TABLE ScheduledMessage(
   ID INT PRIMARY KEY NOT NULL,
   IPADDRESS VARCHAR(255) NOT NULL,
   REQUESTNUMBER INT NOT NULL,
   MEETINGNUMBER INT NOT NULL,
   ROOMNUMBER VARCHAR(255) NOT NULL,
   LISTOFPARTICIPANTS VARCHAR(255)  NOT NULL
);

CREATE TABLE CancelMessage(
   ID INT PRIMARY KEY NOT NULL,
   MEETINGNUMBER INT NOT NULL,
   WHOCANCELED VARCHAR(255) NOT NULL
);

CREATE TABLE NotScheduledMessage(
   ID INT PRIMARY KEY NOT NULL,
   IPADDRESS VARCHAR(255) NOT NULL,
   REQUESTNUMBER INT NOT NULL,
   DATEINSERTED date NOT NULL,
   TIME timestamp NOT NULL,
   MINIMUM int NOT NULL,
   LISTOFPARTICIPANTS VARCHAR(255)  NOT NULL,
   TOPIC VARCHAR(255) NOT NULL
);

CREATE TABLE WithdrawMessage(
   ID INT PRIMARY KEY NOT NULL,
   MEETINGNUMBER INT NOT NULL,
   WHOWITHDRAWED VARCHAR(255) NOT NULL
);

CREATE TABLE AddMessage(
   ID INT PRIMARY KEY NOT NULL,
   MEETINGNUMBER INT NOT NULL,
   WASADDED BOOLEAN NOT NULL,
   WHO VARCHAR(255) NOT NULL
);

CREATE TABLE RoomChangeMessage(
   ID INT PRIMARY KEY NOT NULL,
   MEETINGNUMBER INT NOT NULL,
   LISTOFPARTICIPANTS VARCHAR(255) NOT NULL,
   NEWROOM  VARCHAR(255) NOT NULL
);