

CREATE TABLE RequestMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   REQUESTNUMBER VARCHAR(255) NOT NULL,
   DATEINSERTED date NOT NULL,
   CURRENTTIME time NOT NULL,
   MINIMUM int NOT NULL,
   LISTOFPARTICIPANTS VARCHAR(255) NOT NULL,
   TOPIC VARCHAR(255) NOT NULL
);

CREATE TABLE ResponseMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   REQUESTNUMBER VARCHAR(255) NOT NULL
);

CREATE TABLE InviteMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   DATEINSERTED date NOT NULL,
   TIME time NOT NULL,
   TOPIC VARCHAR(255) NOT NULL,
   REQUESTER VARCHAR(255)  NOT NULL
);

CREATE TABLE AcceptMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   WHOACCEPTED VARCHAR(255) NOT NULL
);

CREATE TABLE RejectMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   WHOREJECTED VARCHAR(255) NOT NULL
);

CREATE TABLE ConfirmMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   ROOMNUMBER VARCHAR(255) NOT NULL
);

CREATE TABLE ScheduledMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   REQUESTNUMBER VARCHAR(255) NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   ROOMNUMBER VARCHAR(255) NOT NULL,
   LISTOFCONFIRMEDPARTICIPANTS VARCHAR(255) NOT NULL
);

CREATE TABLE CancelMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   WHOCANCELED VARCHAR(255) NOT NULL
);

CREATE TABLE NotScheduledMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   REQUESTNUMBER VARCHAR(255) NOT NULL,
   DATEINSERTED date NOT NULL,
   TIME time NOT NULL,
   MINIMUM int NOT NULL,
   LISTOFCONFIRMEDPARTICIPANTS VARCHAR(255) NOT NULL,
   TOPIC VARCHAR(255) NOT NULL
);

CREATE TABLE WithdrawMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   WHOWITHDRAWED VARCHAR(255) NOT NULL
);

CREATE TABLE AddMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   WASADDED BOOLEAN DEFAULT FALSE,
   WHO VARCHAR(255) NOT NULL
);

CREATE TABLE RoomChangeMessage(
   ID SERIAL PRIMARY KEY NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   NEWROOM  VARCHAR(255) NOT NULL
);

CREATE TABLE ParticipantsConfirmed(
   ID SERIAL PRIMARY KEY NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL,
   WHO VARCHAR(255) NOT NULL,
   CONFIRMED BOOLEAN DEFAULT TRUE
);

CREATE TABLE RoomReservation(
   ID SERIAL PRIMARY KEY NOT NULL,
   ROOMNUMBER VARCHAR(255) NOT NULL,
   DATEINSERTED date NOT NULL,
   START_TIME time NOT NULL,
   END_TIME time NOT NULL,
   MEETINGNUMBER VARCHAR(255) NOT NULL
);